export const lightTheme = {
  body: "#FFF",
  text: "#363537",
  toggleBorder: "#FFF",
  background: "#FFFFFF",
  sidebarBackground: "#f0f0f0",
  iconColor: "#F0F0F0",
  bookCount: "#1F1F1F",
  switchOn: "#000",
  navIconBg: "#FFF",
  borderLine: "#eee",
  textColor: "#000",
};
export const darkTheme = {
  body: "#000",
  text: "#FAFAFA",
  toggleBorder: "#3C3C3C",
  background: "#000",
  sidebarBackground: "#1F1F1F",
  iconColor: "#1F1F1F",
  bookCount: "#F9F9F9",
  navIconBg: "#1F1F1F",
  switchOn: "#000",
  borderLine: "#666",
  textColor: "#FFF",
};
